language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
script: bundle exec rspec spec/lib/cache_machine/adapters/rails_spec.rb && bundle exec rspec spec/lib/cache_machine/cache/associations_spec.rb && bundle exec rspec spec/lib/cache_machine/cache/class_timestam_spec.rb && bundle exec rspec spec/lib/cache_machine/cache/collection_spec.rb && bundle exec rspec spec/lib/cache_machine/cache/map_spec.rb && bundle exec rspec spec/lib/cache_machine/cache/mapper_spec.rb && bundle exec rspec spec/lib/cache_machine/cache/resource_spec.rb && bundle exec rspec spec/lib/cache_machine/cache/scope_spec.rb && bundle exec rspec spec/lib/cache_machine/cache/timestamp_builder_spec.rb
